[package]
name = "id3tag"
version = "0.12.0"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A simple application for updating metadata (ID3) information in FLAC, MP3 and MP4 files."
homepage = "https://github.com/evensolberg/id3tools/id3tag/"
repository = "https://github.com/evensolberg/id3tools"
keywords = ["flac", "audio", "parser", "metadata"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ape = "0.4.0"
clap = { version = "3.2.22", features = ["cargo", "color"] }
id3 = "1.3.0"
log = "0.4.17"
metaflac = "0.2.5"
mp4ameta = "0.11.0"
rayon = "1.5.3"
serde = { version = "1.0.145", features = ["derive"] }
shellexpand = "2.1.2"
toml = "0.5.9"
dsf = "0.2.2"

# Our own package
common = { path = "../common" }
image = "0.24.3"

[dev-dependencies]
assay = "0.1.1"

[build-dependencies]
toml = "0.5.9"
serde = { version = "1.0.145", features = ["derive"] }
