[package]
name = "id3tag"
version = "0.1.0"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A simple application for updating ID3 information in FLAC and MP3 files."
homepage = "https://github.com/evensolberg/id3tag"
repository = "https://github.com/evensolberg/id3tag"
keywords = ["flac", "audio", "parser", "metadata"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
env_logger = "0.9.0"
log = "0.4.14"
metaflac = "0.2.5"
