[package]
name = "id3tag"
version = "0.4.2"
edition = "2021"
authors = ["Even Solberg <even.solberg@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A simple application for updating metadata (ID3) information in FLAC, MP3 and MP4 files."
homepage = "https://github.com/evensolberg/id3tag"
repository = "https://github.com/evensolberg/id3tag"
keywords = ["flac", "audio", "parser", "metadata"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
env_logger = "0.9.0"
id3 = "0.6.6"
log = "0.4.14"
metaflac = "0.2.5"
mp4ameta = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.132"
shellexpand = "2.1.0"
toml = "0.5.8"
