[package]
name = "id3cli-gen"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Our own package
common = { path = "../common" }
clap_complete = "4.1.4"
clap_complete_fig = "4.1.1"
clap_mangen = "0.2.9"
log = "0.4.17"
