
# cargo-vet config file

[cargo-vet]
version = "0.6"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.android_system_properties]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.ape]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.arc-swap]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.assay]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.assay-proc-macro]]
version = "0.1.1"
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.bit_field]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.12.0"
criteria = "safe-to-deploy"

[[exemptions.bytemuck]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.cfb]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.23"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.1.8"
criteria = "safe-to-deploy"

[[exemptions.clap_complete]]
version = "4.1.4"
criteria = "safe-to-deploy"

[[exemptions.clap_complete_fig]]
version = "4.1.1"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.clap_mangen]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.codespan-reporting]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.color_quant]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.14"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.15"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ctor]]
version = "0.1.26"
criteria = "safe-to-run"

[[exemptions.cxx]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.cxx-build]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-flags]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.cxxbridge-macro]]
version = "1.0.92"
criteria = "safe-to-deploy"

[[exemptions.derivative]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.destructure_traitobject]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-run"

[[exemptions.dirs]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.3.7"
criteria = "safe-to-deploy"

[[exemptions.dsf]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.errno-dragonfly]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.exr]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.flate2]]
version = "1.0.25"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.10.14"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.26"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.26"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.gif]]
version = "0.11.4"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.53"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.id3]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.24.5"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.2"
criteria = "safe-to-deploy"

[[exemptions.infer]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-run"

[[exemptions.io-lifetimes]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.jpeg-decoder]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.61"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.lebe]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.140"
criteria = "safe-to-deploy"

[[exemptions.link-cplusplus]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.linked-hash-map]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.17"
criteria = "safe-to-deploy"

[[exemptions.log-mdc]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.log4rs]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.metaflac]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.mp3-metadata]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.mp4ameta]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.mp4ameta_proc]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.nanorand]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.num-integer]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.num-rational]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.num-traits]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.num_cpus]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.17.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.os_str_bytes]]
version = "6.4.1"
criteria = "safe-to-deploy"

[[exemptions.output_vt100]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.7"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-run"

[[exemptions.png]]
version = "0.17.7"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.3.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.51"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.quote]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.roff]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.36.9"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.sampled_data_duration]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.scoped_threadpool]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.scratch]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.154"
criteria = "safe-to-deploy"

[[exemptions.serde-value]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.154"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.94"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml]]
version = "0.8.26"
criteria = "safe-to-deploy"

[[exemptions.shellexpand]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.simd-adler32]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.4.0"
criteria = "safe-to-run"

[[exemptions.termcolor]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.terminal_size]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.39"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.39"
criteria = "safe-to-deploy"

[[exemptions.thread-id]]
version = "4.0.0"
criteria = "safe-to-deploy"

[[exemptions.tiff]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.26.0"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.19.4"
criteria = "safe-to-deploy"

[[exemptions.typemap-ors]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.8"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.1.10"
criteria = "safe-to-deploy"

[[exemptions.unsafe-any-ors]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.10.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.84"
criteria = "safe-to-deploy"

[[exemptions.weezl]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.42.0"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.45.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.1"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.zune-inflate]]
version = "0.2.51"
criteria = "safe-to-deploy"
