//! Contains a single function to build the CLI
use clap::{App, Arg, ArgMatches};

/// Builds the CLI so the main file doesn't get cluttered.
pub fn build_cli() -> ArgMatches {
    // This is the heading under which all the tags settings are grouped
    // run the app with `-h` to see.
    let tags_name = "TAGS";
    // use `static because what's returned is used across the application
    App::new(clap::crate_name!())
        .about(clap::crate_description!())
        .version(clap::crate_version!())
        .author(clap::crate_authors!("\n"))
        .long_about(clap::crate_description!())
        .override_usage("id3tag <FILE(S)> [OPTIONS] [TAGS]")
        .arg(
            Arg::new("files")
                .value_name("FILE(S)")
                .help("One or more file(s) to process.")
                .long_help("One or more files to process.  Wildcards and multiple_occurrences files (e.g. 2019*.flac 2020*.mp3) are supported. Use the ** glob to recurse (eg. **/*.mp3). Note: Case sensitive.")
                .takes_value(true)
                .multiple_occurrences(true)
                .required(true)
        )
        .arg( // Debug (hidden)
            Arg::new("debug")
                .short('d')
                .long("debug")
                .multiple_occurrences(true)
                .help("Output debug information as we go. Supply it twice for trace-level logs.")
                .takes_value(false)
                .hide(true)
        )
        .arg( // Don't print any information
            Arg::new("quiet")
                .short('q')
                .long("quiet")
                .multiple_occurrences(false)
                .help("Don't produce any output except errors while working.")
                .takes_value(false)
        )
        .arg( // Stop on error
            Arg::new("stop")
                .short('s')
                .long("stop-on-error")
                .multiple_occurrences(false)
                .help("Stop on error.")
                .long_help("Stop on error. If this flag isn't set, the application will attempt to continue in case of error.")
                .takes_value(false)
        )
        .arg( // Dry-run
            Arg::new("dry-run")
                .short('r')
                .long("dry-run")
                .help("Iterate through the files and produce output without actually processing anything.")
                .multiple_occurrences(false)
                .takes_value(false)
        )
        .arg( // Print summary information
            Arg::new("print-summary")
                .short('p')
                .long("print-summary")
                .multiple_occurrences(false)
                .help("Print summary after all files are processed.")
                .takes_value(false)
        )
        .arg( // Don't export detail information
            Arg::new("detail-off")
                .short('o')
                .long("detail-off")
                .help("Don't display detailed information about each file processed.")
                .multiple_occurrences(false)
                .takes_value(false)
        )
        .arg( // Config file
            Arg::new("config-file")
                .short('c')
                .long("config-file")
                .help("The name of the config file to be read.")
                .long_help("The name of the config file to be read. Note that this is specified WITHOUT the '=', eg. -c myconfig.toml")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .default_missing_value("~/.id3tag-config.toml")
                .display_order(1)
        )
        //////////////////////////////////////////////
        // Options
        .arg( // Album artist
            Arg::new("album-artist")
                .long("album-artist")
                .visible_alias("aa")
                .help("The album artist(s).")
                .long_help("The name of the album artist(s). Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Album artist sort
            Arg::new("album-artist-sort")
                .long("album-artist-sort")
                .visible_alias("aas")
                .help("Album artist(s) sort name.")
                .long_help("The name on which the album artist(s) is sorted. Use quotation marks for multi-word entries. Example: Artist is 'Alicia Keys', but this value may be 'Keys, Alicia'. This is usually set to be the same for all tracks and discs for an album. Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Album title
            Arg::new("album-title")
                .long("album-title")
                .visible_alias("at")
                .help("The album title.")
                .help("The title of the album. Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Album title sort
            Arg::new("album-title-sort")
                .long("album-title-sort")
                .visible_alias("ats")
                .help("The album title sort name.")
                .long_help("The sorting title of the album. Use quotation marks for multi-word entries. Example: Title is 'The Division Bell', but the sorting title is 'Division Bell, The'. Not commonly used.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Disc number
            Arg::new("disc-number")
                .long("disc-number")
                .visible_alias("dn")
                .help("The disc number.")
                .long_help("The disc number for the disc being processed. This would take the form of 'DISCNUMBER (this value) of TOTALDISCS'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
            )
        .arg( // Disc total
            Arg::new("disc-total")
                .long("disc-number-total")
                .visible_alias("dt")
                .help("The total number of discs for the album.")
                .long_help("The total number of discs that make up this album. This would take the form of 'DISCNUMBER of TOTALDISCS (this value)'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Track artist
            Arg::new("track-artist")
                .long("track-artist")
                .visible_alias("ta")
                .help("The track artist.")
                .long_help("The name of the track artist(s). Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Track artist sort
            Arg::new("track-artist-sort")
                .long("track-artist-sort")
                .visible_alias("tas")
                .help("The track artist(s) sort name.")
                .help("The sort name of the track artist(s). Use quotation marks for multi-word entries. Example: Artist is 'Alicia Keys', but this value may be 'Keys, Alicia'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Track title
            Arg::new("track-title")
                .long("track-title")
                .visible_alias("tt")
                .help("The title of the track.")
                .long_help("The title of the track. Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Track title sort
            Arg::new("track-title-sort")
                .long("track-title-sort")
                .visible_alias("tts")
                .help("The sort title of the track.")
                .help("The sort title of the track. Use quotation marks for multi-word entries. This is rarely used.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
        )
        .arg( // Track number
            Arg::new("track-number")
                .long("track-number")
                .visible_alias("tn")
                .help("The track number.")
                .help("The track number. Takes the form of 'TRACKNUMBER (this value) of TOTALTRACKS'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .help_heading(tags_name)
            )
        .arg( // Track total
            Arg::new("track-total")
                .long("track-number-total")
                .visible_alias("to")
                .help("The total number of tracks for the disc.")
                .help("The total number of tracks for the disc. Takes the form of 'TRACKNUMBER of TOTALTRACKS (this value)'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Track genre
            Arg::new("track-genre")
                .long("track-genre")
                .visible_alias("tg")
                .help("The track music genre.")
                .long_help("The track music genre (eg. 'Rock', 'R&B', 'Classical'). This is usually set to the same value for all tracks on a disc or album. Use quotation marks for multi-word entries. Cannot be combined with '--track-genre-number'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Track genre number
            Arg::new("track-genre-number")
                .long("track-genre-number")
                .visible_alias("tgn")
                .help("The track music genre number.")
                .long_help("The track music genre number (eg. 'Rock'=17, 'R&B'=14, 'Classical'=32). This is usually set to the same value for all tracks on a disc or album. Cannot be combined with '--track-genre'. Whichever is passed LAST is used.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false)
                .conflicts_with("track-genre") // works both ways
                .validator(genre_number_validator).help_heading(tags_name)
        )
        .arg( // Track composer
            Arg::new("track-composer")
                .long("track-composer")
                .visible_alias("tc")
                .help("The composer(s) for the track.")
                .help("The composer(s) for the track. Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Track composer sort
            Arg::new("track-composer-sort")
                .long("track-composer-sort")
                .visible_alias("tcs")
                .help("The sort composer(s) for the track.")
                .help("The sort composer(s) for the track. Use quotation marks for multi-word entries. For example, if the composer is 'Ludwig van Beethoven', this value could be 'Beethoven, Ludwig van'.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Track date
            Arg::new("track-date")
                .long("track-date")
                .visible_alias("td")
                .help("The release date for the track.")
                .help("The release date for the track. This is usually the album release date. Can be a year or a date.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Track comments
            Arg::new("track-comments")
                .long("track-comments")
                .visible_alias("tm")
                .help("The comments for the track.")
                .help("The comments for the track. Use quotation marks for multi-word entries.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Front cover picture
            Arg::new("picture-front")
                .long("picture-front")
                .visible_alias("pf")
                .help("The front cover picture file name.")
                .long_help("The front cover picture file name. Example: 'cover-front.jpg'. Looks for the cover picture alongside the music first, then in the invocation directory.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Back cover picture
            Arg::new("picture-back")
                .long("picture-back")
                .visible_alias("pb")
                .help("The back cover picture file name.")
                .long_help("The back cover picture file name. Example: 'cover-back.jpg'. Looks for the cover picture alongside the music first, then in the invocation directory.")
                .takes_value(true)
                .multiple_occurrences(false)
                .require_equals(false).help_heading(tags_name)
        )
        .arg( // Tags (Hidden)
            Arg::new(tags_name)
                .long(tags_name)
                .short('t')
                .help("The tags you wish to set in the form `key1=value1, key2=value2`. Note the space between entries!")
                .takes_value(true)
                .multiple_occurrences(true)
                .require_equals(false)
                .hide(true).help_heading(tags_name)
        )
        .get_matches()
}

/// Checks that the specified genre number is in the valid range (0..=191)
fn genre_number_validator(input: &str) -> Result<(), String> {
    let genre_num = u16::from_str_radix(input, 16);
    match genre_num {
        Ok(gn) => {
            if gn <= 191 {
                Ok(())
            } else {
                Err(String::from("track-genre-number must be 0-191."))
            }
        }
        Err(_) => Err(String::from(
            "Unable to parse the input provided to --track-genre-number.",
        )),
    }
}
