//! Contains a single function to build the main CLI for the `id3tag` program.
//! This is also used by the `id3cli-gen` program to generate the CLI completion tags for Fig, Bash, etc.
use clap::{Arg, ArgAction, Command};

/// Builds the CLI so the main file doesn't get cluttered. Note that the `<'static>` means it returns a global variable.
#[must_use]
pub fn build_cli(version: &'static str) -> Command {
    // This is the heading under which all the tags settings are grouped
    // run the app with `-h` to see.
    let tags_name = "TAGS";
    let operations_name = "OPERATIONS";
    let images_name = "IMAGES";

    Command::new("id3tag")
        .about("A simple application for updating metadata (ID3) information in music files.")
        .version(version)
        .author(clap::crate_authors!("\n"))
        .long_about("A simple application for updating metadata (ID3) information in music files.")
        .override_usage("id3tag <FILE(S)> [OPTIONS] [TAGS]")
        .arg( // Files - the files to process
            Arg::new("files")
                .value_name("FILE(S)")
                .help("One or more file(s) to process.")
                .long_help("One or more files to process.  Wildcards and multiple_occurrences files (e.g. 2019*.flac 2020*.mp3) are supported. Use the ** glob to recurse (eg. **/*.mp3). Note: Case sensitive.")
                .num_args(1..)
                .required(true)
                .action(ArgAction::Append)
        )
        .arg( // Stop on error
            Arg::new("stop-on-error")
                .short('s')
                .long("stop-on-error")
                .help("Stop on error.")
                .long_help("Stop on error. If this flag isn't set, the application will attempt to continue in case of error.")
                .num_args(0)
                .action(ArgAction::SetTrue)
        )
        .arg( // Dry-run
            Arg::new("dry-run")
                .short('r')
                .long("dry-run")
                .help("Iterate through the files and produce output without actually processing anything.")
                .num_args(0)
                .action(ArgAction::SetTrue)
        )
        .arg( // Print summary information
            Arg::new("print-summary")
                .short('p')
                .long("print-summary")
                .help("Print summary after all files are processed.")
                .num_args(0)
                .action(ArgAction::SetTrue)
        )
        .arg( // Don't export detail information
            Arg::new("detail-off")
                .short('o')
                .long("detail-off")
                .help("Don't display detailed information about each file processed.")
                .num_args(0)
                .action(ArgAction::SetTrue)
        )
        .arg( // Don't export detail information
            Arg::new("single-thread")
                .short('1')
                .long("single-thread")
                .help("Run processing single-threaded. Takes longer, but has less impact on the system.")
                .num_args(0)
                .action(ArgAction::SetTrue)
        )
        .arg( // Config file
            Arg::new("config-file")
                .short('c')
                .long("config-file")
                .help("The name of the config file to be read.")
                .long_help("The name of the config file to be read. Note that this is specified WITHOUT the '=', eg. -c myconfig.toml")
                .num_args(..=1)
                .require_equals(false)
                .default_missing_value("~/.config/id3tag/config.toml")
                .display_order(1)
                .action(ArgAction::Set)
        )
        .arg( // Log config
            Arg::new("log-config-file")
                .short('l')
                .long("log-config-file")
                .help("The name of the YAML file containing the logging settings.")
                .num_args(..=1)
                .require_equals(false)
                .default_missing_value("~/.config/id3tag/id3tag-logs.yaml")
                .display_order(2)
                .action(ArgAction::Set)
        )
        //////////////////////////////////////////////
        // Options
        .arg( // Album artist
            Arg::new("album-artist")
                .long("album-artist")
                .visible_alias("aa")
                .help("The album artist(s).")
                .long_help("The name of the album artist(s). Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Album artist sort
            Arg::new("album-artist-sort")
                .long("album-artist-sort")
                .visible_alias("aas")
                .help("Album artist(s) sort name.")
                .long_help("The name on which the album artist(s) is sorted. Use quotation marks for multi-word entries. Example: Artist is 'Alicia Keys', but this value may be 'Keys, Alicia'. This is usually set to be the same for all tracks and discs for an album. Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Album title
            Arg::new("album-title")
                .long("album-title")
                .visible_alias("at")
                .help("The album title.")
                .help("The title of the album. Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Album title sort
            Arg::new("album-title-sort")
                .long("album-title-sort")
                .visible_alias("ats")
                .help("The album title sort name.")
                .long_help("The sorting title of the album. Use quotation marks for multi-word entries. Example: Title is 'The Division Bell', but the sorting title is 'Division Bell, The'. Not commonly used.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Disc number
            Arg::new("disc-number")
                .long("disc-number")
                .visible_alias("dn")
                .help("The disc number.")
                .long_help("The disc number for the disc being processed. This would take the form of 'DISCNUMBER (this value) of TOTALDISCS'.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
            )
        .arg( // Determine disc number automagically
            Arg::new("disc-number-count")
                .long("disc-number-count")
                .visible_alias("dnc")
                .help("Determine the disc number and total number of discs based on the folder structure.")
                .long_help("Tries to determine disc number and total number of discs for the disc being processed based on whether we're in a subdirectory called 'CD xx' or 'Disc xx' etc. If not, assumes the disc number to be 1.")
                .num_args(0)
                .require_equals(false)
                .conflicts_with("disc-number")
                .conflicts_with("disc-total")
                .help_heading(tags_name)
                .action(ArgAction::SetTrue)
            )
        .arg( // Disc total
            Arg::new("disc-total")
                .long("disc-number-total")
                .visible_alias("dt")
                .help("The total number of discs for the album.")
                .long_help("The total number of discs that make up this album. This would take the form of 'DISCNUMBER of TOTALDISCS (this value)'.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track artist
            Arg::new("track-artist")
                .long("track-artist")
                .visible_alias("ta")
                .help("The track artist.")
                .long_help("The name of the track artist(s). Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track artist
            Arg::new("track-album-artist")
                .long("track-album-artist")
                .visible_alias("taa")
                .help("Set album and track artist to be the same value.")
                .long_help("Sets both the album artist and track artist to the value provided.")
                .num_args(1)
                .require_equals(false)
                .conflicts_with("track-artist")
                .conflicts_with("album-artist")
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track artist sort
            Arg::new("track-artist-sort")
                .long("track-artist-sort")
                .visible_alias("tas")
                .help("The track artist(s) sort name.")
                .help("The sort name of the track artist(s). Use quotation marks for multi-word entries. Example: Artist is 'Alicia Keys', but this value may be 'Keys, Alicia'.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track title
            Arg::new("track-title")
                .long("track-title")
                .visible_alias("tt")
                .help("The title of the track.")
                .long_help("The title of the track. Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track title sort
            Arg::new("track-title-sort")
                .long("track-title-sort")
                .visible_alias("tts")
                .help("The sort title of the track.")
                .long_help("The sort title of the track. Use quotation marks for multi-word entries. This is rarely used.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track number
            Arg::new("track-number")
                .long("track-number")
                .visible_alias("tn")
                .help("The track number.")
                .long_help("The track number. Takes the form of 'TRACKNUMBER (this value) of TOTALTRACKS'.")
                .num_args(1)
                .require_equals(false)
                .help_heading(tags_name)
                .action(ArgAction::Set)
            )
        .arg( // Track total
            Arg::new("track-total")
                .long("track-number-total")
                .visible_alias("to")
                .help("The total number of tracks for the disc.")
                .long_help("The total number of tracks for the disc. Takes the form of 'TRACKNUMBER of TOTALTRACKS (this value)'.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track count
            Arg::new("track-count")
                .long("track-number-count")
                .visible_alias("tnc")
                .help("Use number of files as total number of tracks.")
                .long_help("Counts the number of files with the same extension in the same subdirectory, and uses it as the total number of tracks for the disc.")
                .num_args(1)
                .conflicts_with("track-total")
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track genre
            Arg::new("track-genre")
                .long("track-genre")
                .visible_alias("tg")
                .help("The track music genre.")
                .long_help("The track music genre (eg. 'Rock', 'R&B', 'Classical'). This is usually set to the same value for all tracks on a disc or album. Use quotation marks for multi-word entries. Cannot be combined with '--cdumber'.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track genre number
            Arg::new("track-genre-number")
                .long("track-genre-number")
                .visible_alias("tgn")
                .help("The track music genre number.")
                .long_help("The track music genre number (eg. 'Rock'=17, 'R&B'=14, 'Classical'=32). This is usually set to the same value for all tracks on a disc or album. Cannot be combined with '--track-genre'. Whichever is passed LAST is used.")
                .num_args(1)
                .require_equals(false)
                .conflicts_with("track-genre") // works both ways
                .value_parser(clap::value_parser!(u16).range(0..=191))
                .help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track composer
            Arg::new("track-composer")
                .long("track-composer")
                .visible_alias("tc")
                .help("The composer(s) for the track.")
                .help("The composer(s) for the track. Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track composer sort
            Arg::new("track-composer-sort")
                .long("track-composer-sort")
                .visible_alias("tcs")
                .help("The sort composer(s) for the track.")
                .help("The sort composer(s) for the track. Use quotation marks for multi-word entries. For example, if the composer is 'Ludwig van Beethoven', this value could be 'Beethoven, Ludwig van'.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track date
            Arg::new("track-date")
                .long("track-date")
                .visible_alias("td")
                .help("The release date for the track.")
                .help("The release date for the track. This is usually the album release date. Can be a year or a date.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Track comments
            Arg::new("track-comments")
                .long("track-comments")
                .visible_alias("tm")
                .help("The comments for the track.")
                .help("The comments for the track. Use quotation marks for multi-word entries.")
                .num_args(1)
                .require_equals(false).help_heading(tags_name)
                .action(ArgAction::Set)
        )
        .arg( // Front cover picture candidate
            Arg::new("picture-front-candidate")
                .long("picture-front-candidate")
                .visible_alias("pfc")
                .help("The front cover picture candidate file name.")
                .long_help("The front cover picture candidate file name. Example: 'front.jpg' or 'folder.jpg'. Looks for the cover picture alongside the music first, then in the parent folder, then in any directories supplied using the `--picture-search-folder` argument.")
                .num_args(1..)
                .require_equals(false).help_heading(images_name)
                .action(ArgAction::Append)
        )
        .arg( // Front cover picture candidate
            Arg::new("picture-back-candidate")
                .long("picture-back-candidate")
                .visible_alias("pbc")
                .help("The back cover picture candidate file name.")
                .long_help("The back cover picture candidate file name. Example: 'back.jpg' or 'back-cover.jpg'. Looks for the cover picture alongside the music first, then in the parent folder, then in any directories supplied using the `--picture-search-folder` argument.")
                .num_args(1..)
                .require_equals(false).help_heading(images_name)
                .action(ArgAction::Append)
        )
        .arg( // Picture search folder
            Arg::new("picture-search-folder")
                .long("picture-search-folder")
                .visible_alias("psf")
                .help("Folder(s) in which to look for the candidate front and back covers.")
                .long_help("The folder(s) to seach for the candidate cover images. Can be either relative to the music file ('../Artwork') or absolute ('/users/me/Documents/images').")
                .num_args(1..)
                .default_missing_value(".")
                .require_equals(false).help_heading(images_name)
                .action(ArgAction::Append)
        )
        .arg( // Picture max size
            Arg::new("picture-max-size")
                .long("picture-max-size")
                .visible_alias("pms")
                .help("Picture maximum size in pixels for the longest edge.")
                .long_help("The number of pixels for the longest edge of the cover picture. The default is '0', which means no maximum size.")
                .num_args(1)
                .default_missing_value("0")
                .require_equals(false).help_heading(images_name)
                .action(ArgAction::Set)
        )
        // .arg( // Tags (Hidden)
        //     Arg::new("tags")
        //         .long("tags")
        //         .short('t')
        //         .help("The tags you wish to set in the form `key1=value1, key2=value2`. Note the space between entries!")
        //         .num_args(1..)
        //         .require_equals(true)
        //         .hide(true).help_heading(tags_name)
        //         .action(ArgAction::Append)
        // )
        .arg( // Rename file
            Arg::new("rename-file")
                .long("rename-file")
                .visible_alias("rf")
                .help("Renames the music file after setting the tags. Example: \"%dn-%tn %tt\"")
                .num_args(1)
                .require_equals(false)
                .required(false)
                .hide(false).help_heading(operations_name)
                .display_order(1)
                .action(ArgAction::Set)
        )
}
