use clap::{Arg, Command}; // Command line

pub fn build_cli() -> Command {
    Command::new(clap::crate_name!())
        .about(clap::crate_description!())
        .version(clap::crate_version!())
        .author(clap::crate_authors!("\n"))
        .long_about("Show the metadata header of music files.")
        .arg(
            Arg::new("files")
                .value_name("FILE(S)")
                .help("One or more file(s) to process. Globs, wildcards and multiple files (e.g. *.mp3 Genesis/**/*.flac) are supported.")
                .num_args(1..),
        )
        .arg( // Print summary information
            Arg::new("print-summary")
                .short('p')
                .long("print-summary")
                .help("Print summary detail for each session processed.")
                .num_args(0)
                .action(clap::ArgAction::SetTrue)
        )
        .arg( // Don't export detail information
            Arg::new("debug")
                .short('d')
                .long("debug")
                .help("Show debug information.")
                .num_args(0)
                .action(clap::ArgAction::Count)
                .hide(true)
        )
        .arg( // Don't export detail information
            Arg::new("show-detail")
                .short('o')
                .long("show-detail")
                .help("Show detailed information about each file processed.")
                .num_args(0)
                .action(clap::ArgAction::SetTrue)
        )
        .arg( // CSV detail output file name
            Arg::new("csv-file")
                .short('c')
                .long("csv-file")
                .help("The name of the CSV into which the detailed information for each file is to be written.")
                .num_args(0..)
                .default_missing_value("details.csv")
                .display_order(2)
                .action(clap::ArgAction::Set)
        )
        .arg( // CSV summary output file name
            Arg::new("summary-file")
                .short('s')
                .long("summary-file")
                .help("The name of the CSV into which summary information is to be written.")
                .num_args(0..)
                .default_missing_value("summary.csv")
                .display_order(2)
                .action(clap::ArgAction::Set)
        )
}
